"""add contractors table

Revision ID: 115a11c4d130
Revises: f0ed35d0ba7e
Create Date: 2026-04-06 07:57:57.337202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115a11c4d130'
down_revision: Union[str, Sequence[str], None] = 'f0ed35d0ba7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_individual', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('ogrn', sa.String(length=15), nullable=False),
    sa.Column('legal_address', sa.String(length=500), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bik', sa.String(length=9), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('corr_account', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractor_disciplines',
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contractor_disciplines')
    op.drop_table('contractors')
    # ### end Alembic commands ###
