"""initial

Revision ID: 126bc221cf73
Revises: 
Create Date: 2026-04-06 02:40:19.536040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126bc221cf73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_individual', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('ogrn', sa.String(length=15), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('legal_address', sa.String(length=500), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bik', sa.String(length=9), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('corr_account', sa.String(length=20), nullable=False),
    sa.Column('signer_name', sa.String(length=255), nullable=False),
    sa.Column('signer_role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contractor_keycloak_id', sa.String(length=100), nullable=False),
    sa.Column('contractor_full_name', sa.String(length=255), nullable=False),
    sa.Column('contractor_inn', sa.String(length=12), nullable=False),
    sa.Column('contractor_ogrn', sa.String(length=15), nullable=False),
    sa.Column('contractor_is_individual', sa.Boolean(), nullable=False),
    sa.Column('contractor_legal_address', sa.String(length=500), nullable=False),
    sa.Column('contractor_bank_name', sa.String(length=255), nullable=False),
    sa.Column('contractor_bik', sa.String(length=9), nullable=False),
    sa.Column('contractor_account', sa.String(length=20), nullable=False),
    sa.Column('contractor_corr_account', sa.String(length=20), nullable=False),
    sa.Column('object_full_name', sa.String(length=500), nullable=False),
    sa.Column('object_address', sa.String(length=500), nullable=True),
    sa.Column('basis_enabled', sa.Boolean(), nullable=False),
    sa.Column('basis_type', sa.String(length=100), nullable=True),
    sa.Column('basis_number', sa.String(length=100), nullable=True),
    sa.Column('basis_date', sa.Date(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_included', sa.Boolean(), nullable=False),
    sa.Column('tranch1_pct', sa.Integer(), nullable=False),
    sa.Column('tranch1_condition', sa.String(length=500), nullable=False),
    sa.Column('tranch2_pct', sa.Integer(), nullable=True),
    sa.Column('tranch2_condition', sa.String(length=500), nullable=True),
    sa.Column('tranch3_pct', sa.Integer(), nullable=True),
    sa.Column('tranch3_condition', sa.String(length=500), nullable=True),
    sa.Column('extra_conditions', sa.Text(), nullable=True),
    sa.Column('works_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_templates')
    op.drop_table('contracts')
    op.drop_table('disciplines')
    op.drop_table('customers')
    # ### end Alembic commands ###
