"""add signer_role_nominative

Revision ID: 608f78ad1b2b
Revises: 769df0b0de62
Create Date: 2026-04-06 06:43:13.263378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608f78ad1b2b'
down_revision: Union[str, Sequence[str], None] = '769df0b0de62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('signer_role_nominative', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'signer_role_nominative')
    # ### end Alembic commands ###
