"""add contractor_phone

Revision ID: 769df0b0de62
Revises: 32ae70f8c63f
Create Date: 2026-04-06 06:31:50.400140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769df0b0de62'
down_revision: Union[str, Sequence[str], None] = '32ae70f8c63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contractor_phone', sa.String(length=20), nullable=True))
    op.add_column('contracts', sa.Column('works_stages', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('works_results', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'works_results')
    op.drop_column('contracts', 'works_stages')
    op.drop_column('contracts', 'contractor_phone')
    # ### end Alembic commands ###
