"""add signer_name_genitive

Revision ID: 9bb348cec40a
Revises: 126bc221cf73
Create Date: 2026-04-06 04:15:35.080622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb348cec40a'
down_revision: Union[str, Sequence[str], None] = '126bc221cf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('signer_name_genitive', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'signer_name_genitive')
    # ### end Alembic commands ###
