"""add full_name_extended

Revision ID: f0ed35d0ba7e
Revises: 608f78ad1b2b
Create Date: 2026-04-06 07:12:52.062915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ed35d0ba7e'
down_revision: Union[str, Sequence[str], None] = '608f78ad1b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('full_name_extended', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'full_name_extended')
    # ### end Alembic commands ###
