"""add project_objects table

Revision ID: f4c964b48009
Revises: aa72573aae4b
Create Date: 2026-04-06 09:56:36.426525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c964b48009'
down_revision: Union[str, Sequence[str], None] = 'aa72573aae4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('basis_enabled', sa.Boolean(), nullable=False),
    sa.Column('basis_type', sa.String(length=100), nullable=True),
    sa.Column('basis_number', sa.String(length=100), nullable=True),
    sa.Column('basis_date', sa.Date(), nullable=True),
    sa.Column('basis_object', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_contractors',
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['project_objects.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object_contractors')
    op.drop_table('project_objects')
    # ### end Alembic commands ###
